################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/wolfcrypt/src/aes.c \
../src/wolfcrypt/src/arc4.c \
../src/wolfcrypt/src/asm.c \
../src/wolfcrypt/src/asn.c \
../src/wolfcrypt/src/blake2b.c \
../src/wolfcrypt/src/blake2s.c \
../src/wolfcrypt/src/camellia.c \
../src/wolfcrypt/src/chacha.c \
../src/wolfcrypt/src/chacha20_poly1305.c \
../src/wolfcrypt/src/cmac.c \
../src/wolfcrypt/src/coding.c \
../src/wolfcrypt/src/compress.c \
../src/wolfcrypt/src/cpuid.c \
../src/wolfcrypt/src/cryptocb.c \
../src/wolfcrypt/src/curve25519.c \
../src/wolfcrypt/src/curve448.c \
../src/wolfcrypt/src/des3.c \
../src/wolfcrypt/src/dh.c \
../src/wolfcrypt/src/dsa.c \
../src/wolfcrypt/src/ecc.c \
../src/wolfcrypt/src/ecc_fp.c \
../src/wolfcrypt/src/eccsi.c \
../src/wolfcrypt/src/ed25519.c \
../src/wolfcrypt/src/ed448.c \
../src/wolfcrypt/src/error.c \
../src/wolfcrypt/src/evp.c \
../src/wolfcrypt/src/falcon.c \
../src/wolfcrypt/src/fe_448.c \
../src/wolfcrypt/src/fe_low_mem.c \
../src/wolfcrypt/src/fe_operations.c \
../src/wolfcrypt/src/ge_448.c \
../src/wolfcrypt/src/ge_low_mem.c \
../src/wolfcrypt/src/ge_operations.c \
../src/wolfcrypt/src/hash.c \
../src/wolfcrypt/src/hmac.c \
../src/wolfcrypt/src/integer.c \
../src/wolfcrypt/src/kdf.c \
../src/wolfcrypt/src/logging.c \
../src/wolfcrypt/src/md2.c \
../src/wolfcrypt/src/md4.c \
../src/wolfcrypt/src/md5.c \
../src/wolfcrypt/src/memory.c \
../src/wolfcrypt/src/misc.c \
../src/wolfcrypt/src/pkcs12.c \
../src/wolfcrypt/src/pkcs7.c \
../src/wolfcrypt/src/poly1305.c \
../src/wolfcrypt/src/pwdbased.c \
../src/wolfcrypt/src/random.c \
../src/wolfcrypt/src/rc2.c \
../src/wolfcrypt/src/ripemd.c \
../src/wolfcrypt/src/rsa.c \
../src/wolfcrypt/src/sakke.c \
../src/wolfcrypt/src/sha.c \
../src/wolfcrypt/src/sha256.c \
../src/wolfcrypt/src/sha3.c \
../src/wolfcrypt/src/sha512.c \
../src/wolfcrypt/src/signature.c \
../src/wolfcrypt/src/siphash.c \
../src/wolfcrypt/src/sp_arm32.c \
../src/wolfcrypt/src/sp_arm64.c \
../src/wolfcrypt/src/sp_armthumb.c \
../src/wolfcrypt/src/sp_c32.c \
../src/wolfcrypt/src/sp_c64.c \
../src/wolfcrypt/src/sp_cortexm.c \
../src/wolfcrypt/src/sp_dsp32.c \
../src/wolfcrypt/src/sp_int.c \
../src/wolfcrypt/src/sp_x86_64.c \
../src/wolfcrypt/src/srp.c \
../src/wolfcrypt/src/tfm.c \
../src/wolfcrypt/src/wc_dsp.c \
../src/wolfcrypt/src/wc_encrypt.c \
../src/wolfcrypt/src/wc_pkcs11.c \
../src/wolfcrypt/src/wc_port.c \
../src/wolfcrypt/src/wolfevent.c \
../src/wolfcrypt/src/wolfmath.c 

LST += \
aes.lst \
arc4.lst \
asm.lst \
asn.lst \
blake2b.lst \
blake2s.lst \
camellia.lst \
chacha.lst \
chacha20_poly1305.lst \
cmac.lst \
coding.lst \
compress.lst \
cpuid.lst \
cryptocb.lst \
curve25519.lst \
curve448.lst \
des3.lst \
dh.lst \
dsa.lst \
ecc.lst \
ecc_fp.lst \
eccsi.lst \
ed25519.lst \
ed448.lst \
error.lst \
evp.lst \
falcon.lst \
fe_448.lst \
fe_low_mem.lst \
fe_operations.lst \
ge_448.lst \
ge_low_mem.lst \
ge_operations.lst \
hash.lst \
hmac.lst \
integer.lst \
kdf.lst \
logging.lst \
md2.lst \
md4.lst \
md5.lst \
memory.lst \
misc.lst \
pkcs12.lst \
pkcs7.lst \
poly1305.lst \
pwdbased.lst \
random.lst \
rc2.lst \
ripemd.lst \
rsa.lst \
sakke.lst \
sha.lst \
sha256.lst \
sha3.lst \
sha512.lst \
signature.lst \
siphash.lst \
sp_arm32.lst \
sp_arm64.lst \
sp_armthumb.lst \
sp_c32.lst \
sp_c64.lst \
sp_cortexm.lst \
sp_dsp32.lst \
sp_int.lst \
sp_x86_64.lst \
srp.lst \
tfm.lst \
wc_dsp.lst \
wc_encrypt.lst \
wc_pkcs11.lst \
wc_port.lst \
wolfevent.lst \
wolfmath.lst 

C_DEPS += \
./src/wolfcrypt/src/aes.d \
./src/wolfcrypt/src/arc4.d \
./src/wolfcrypt/src/asm.d \
./src/wolfcrypt/src/asn.d \
./src/wolfcrypt/src/blake2b.d \
./src/wolfcrypt/src/blake2s.d \
./src/wolfcrypt/src/camellia.d \
./src/wolfcrypt/src/chacha.d \
./src/wolfcrypt/src/chacha20_poly1305.d \
./src/wolfcrypt/src/cmac.d \
./src/wolfcrypt/src/coding.d \
./src/wolfcrypt/src/compress.d \
./src/wolfcrypt/src/cpuid.d \
./src/wolfcrypt/src/cryptocb.d \
./src/wolfcrypt/src/curve25519.d \
./src/wolfcrypt/src/curve448.d \
./src/wolfcrypt/src/des3.d \
./src/wolfcrypt/src/dh.d \
./src/wolfcrypt/src/dsa.d \
./src/wolfcrypt/src/ecc.d \
./src/wolfcrypt/src/ecc_fp.d \
./src/wolfcrypt/src/eccsi.d \
./src/wolfcrypt/src/ed25519.d \
./src/wolfcrypt/src/ed448.d \
./src/wolfcrypt/src/error.d \
./src/wolfcrypt/src/evp.d \
./src/wolfcrypt/src/falcon.d \
./src/wolfcrypt/src/fe_448.d \
./src/wolfcrypt/src/fe_low_mem.d \
./src/wolfcrypt/src/fe_operations.d \
./src/wolfcrypt/src/ge_448.d \
./src/wolfcrypt/src/ge_low_mem.d \
./src/wolfcrypt/src/ge_operations.d \
./src/wolfcrypt/src/hash.d \
./src/wolfcrypt/src/hmac.d \
./src/wolfcrypt/src/integer.d \
./src/wolfcrypt/src/kdf.d \
./src/wolfcrypt/src/logging.d \
./src/wolfcrypt/src/md2.d \
./src/wolfcrypt/src/md4.d \
./src/wolfcrypt/src/md5.d \
./src/wolfcrypt/src/memory.d \
./src/wolfcrypt/src/misc.d \
./src/wolfcrypt/src/pkcs12.d \
./src/wolfcrypt/src/pkcs7.d \
./src/wolfcrypt/src/poly1305.d \
./src/wolfcrypt/src/pwdbased.d \
./src/wolfcrypt/src/random.d \
./src/wolfcrypt/src/rc2.d \
./src/wolfcrypt/src/ripemd.d \
./src/wolfcrypt/src/rsa.d \
./src/wolfcrypt/src/sakke.d \
./src/wolfcrypt/src/sha.d \
./src/wolfcrypt/src/sha256.d \
./src/wolfcrypt/src/sha3.d \
./src/wolfcrypt/src/sha512.d \
./src/wolfcrypt/src/signature.d \
./src/wolfcrypt/src/siphash.d \
./src/wolfcrypt/src/sp_arm32.d \
./src/wolfcrypt/src/sp_arm64.d \
./src/wolfcrypt/src/sp_armthumb.d \
./src/wolfcrypt/src/sp_c32.d \
./src/wolfcrypt/src/sp_c64.d \
./src/wolfcrypt/src/sp_cortexm.d \
./src/wolfcrypt/src/sp_dsp32.d \
./src/wolfcrypt/src/sp_int.d \
./src/wolfcrypt/src/sp_x86_64.d \
./src/wolfcrypt/src/srp.d \
./src/wolfcrypt/src/tfm.d \
./src/wolfcrypt/src/wc_dsp.d \
./src/wolfcrypt/src/wc_encrypt.d \
./src/wolfcrypt/src/wc_pkcs11.d \
./src/wolfcrypt/src/wc_port.d \
./src/wolfcrypt/src/wolfevent.d \
./src/wolfcrypt/src/wolfmath.d 

OBJS += \
./src/wolfcrypt/src/aes.o \
./src/wolfcrypt/src/arc4.o \
./src/wolfcrypt/src/asm.o \
./src/wolfcrypt/src/asn.o \
./src/wolfcrypt/src/blake2b.o \
./src/wolfcrypt/src/blake2s.o \
./src/wolfcrypt/src/camellia.o \
./src/wolfcrypt/src/chacha.o \
./src/wolfcrypt/src/chacha20_poly1305.o \
./src/wolfcrypt/src/cmac.o \
./src/wolfcrypt/src/coding.o \
./src/wolfcrypt/src/compress.o \
./src/wolfcrypt/src/cpuid.o \
./src/wolfcrypt/src/cryptocb.o \
./src/wolfcrypt/src/curve25519.o \
./src/wolfcrypt/src/curve448.o \
./src/wolfcrypt/src/des3.o \
./src/wolfcrypt/src/dh.o \
./src/wolfcrypt/src/dsa.o \
./src/wolfcrypt/src/ecc.o \
./src/wolfcrypt/src/ecc_fp.o \
./src/wolfcrypt/src/eccsi.o \
./src/wolfcrypt/src/ed25519.o \
./src/wolfcrypt/src/ed448.o \
./src/wolfcrypt/src/error.o \
./src/wolfcrypt/src/evp.o \
./src/wolfcrypt/src/falcon.o \
./src/wolfcrypt/src/fe_448.o \
./src/wolfcrypt/src/fe_low_mem.o \
./src/wolfcrypt/src/fe_operations.o \
./src/wolfcrypt/src/ge_448.o \
./src/wolfcrypt/src/ge_low_mem.o \
./src/wolfcrypt/src/ge_operations.o \
./src/wolfcrypt/src/hash.o \
./src/wolfcrypt/src/hmac.o \
./src/wolfcrypt/src/integer.o \
./src/wolfcrypt/src/kdf.o \
./src/wolfcrypt/src/logging.o \
./src/wolfcrypt/src/md2.o \
./src/wolfcrypt/src/md4.o \
./src/wolfcrypt/src/md5.o \
./src/wolfcrypt/src/memory.o \
./src/wolfcrypt/src/misc.o \
./src/wolfcrypt/src/pkcs12.o \
./src/wolfcrypt/src/pkcs7.o \
./src/wolfcrypt/src/poly1305.o \
./src/wolfcrypt/src/pwdbased.o \
./src/wolfcrypt/src/random.o \
./src/wolfcrypt/src/rc2.o \
./src/wolfcrypt/src/ripemd.o \
./src/wolfcrypt/src/rsa.o \
./src/wolfcrypt/src/sakke.o \
./src/wolfcrypt/src/sha.o \
./src/wolfcrypt/src/sha256.o \
./src/wolfcrypt/src/sha3.o \
./src/wolfcrypt/src/sha512.o \
./src/wolfcrypt/src/signature.o \
./src/wolfcrypt/src/siphash.o \
./src/wolfcrypt/src/sp_arm32.o \
./src/wolfcrypt/src/sp_arm64.o \
./src/wolfcrypt/src/sp_armthumb.o \
./src/wolfcrypt/src/sp_c32.o \
./src/wolfcrypt/src/sp_c64.o \
./src/wolfcrypt/src/sp_cortexm.o \
./src/wolfcrypt/src/sp_dsp32.o \
./src/wolfcrypt/src/sp_int.o \
./src/wolfcrypt/src/sp_x86_64.o \
./src/wolfcrypt/src/srp.o \
./src/wolfcrypt/src/tfm.o \
./src/wolfcrypt/src/wc_dsp.o \
./src/wolfcrypt/src/wc_encrypt.o \
./src/wolfcrypt/src/wc_pkcs11.o \
./src/wolfcrypt/src/wc_port.o \
./src/wolfcrypt/src/wolfevent.o \
./src/wolfcrypt/src/wolfmath.o 

MAP += \
wolflib.map 


# Each subdirectory must supply rules for building sources it contributes
src/wolfcrypt/src/%.o: ../src/wolfcrypt/src/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-O0 -ffunction-sections -fdata-sections -fdiagnostics-parseable-fixits -Wstack-usage=100 -g2 -mcpu=rx72t -misa=v3 -mlittle-endian-data -I"C:\\Users\\nekom\\e2_studio\\e2sss_proj\\wolflib\\src" -I"C:\\Users\\nekom\\e2_studio\\e2sss_proj\\wolflib\\src\\wolfcrypt\\src" -DWOLFSSL_USER_SETTINGS -DDEBUG_WOLFSSL -Wa,-adlnh="$(basename $(notdir $<)).lst" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" "$<" -c -o "$@")
	@echo $< && rx-elf-gcc @"$@.in"

